apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: msa-payment-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/MSA-payment
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  jobs:
    postSubmit:
      - name: build-and-push
        image: quay.io/buildah/stable
        script: |
          buildah bud --tls-verify=false --storage-driver=vfs --format docker -f ./payment/Dockerfile -t $IMAGE_URL:${CI_HEAD_REF#refs/heads/} .
          buildah push --tls-verify=false --storage-driver=vfs $IMAGE_URL:${CI_HEAD_REF#refs/tags/} docker://$IMAGE_URL:${CI_HEAD_REF#refs/heads/}
        env:
          - name: IMAGE_URL
            value: tmaxcloudck/example-payment
        securityContext:
          privileged: true
        when:
          branch:
            - main
